font_family JetBrainsMono Nerd Font
font_size 9
background #080d10
foreground #d7dbd2
background_opacity 0.60
window_padding_width 8
confirm_os_window_close 0
cursor_shape beam
remember_window_size no
