[Appearance]
color_scheme_path=
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[Palette]
active_colors=#ffd7dbd2, #ff080d10, #ff0f1a1d, #ff122124, #ff9db6ad, #ffc3ccb8, #ffd7dbd2, #ffd7dbd2, #ffd7dbd2, #ff080d10, #ff080d10, #ff0f1a1d, #ff9db6ad, #ff080d10, #ff9db6ad, #ffb9828d, #ff0f1a1d, #ffd7dbd2, #ff0f1a1d, #ffd7dbd2, #808b9892
disabled_colors=#ff5f6f6b, #ff080d10, #ff0f1a1d, #ff122124, #ff5f6f6b, #ff5f6f6b, #ff5f6f6b, #ff5f6f6b, #ff5f6f6b, #ff080d10, #ff080d10, #ff0f1a1d, #ff5f6f6b, #ff080d10, #ff5f6f6b, #ff5f6f6b, #ff0f1a1d, #ff5f6f6b, #ff0f1a1d, #ff5f6f6b, #808b9892
inactive_colors=#ffd7dbd2, #ff080d10, #ff0f1a1d, #ff122124, #ff9db6ad, #ffc3ccb8, #ffd7dbd2, #ffd7dbd2, #ffd7dbd2, #ff080d10, #ff080d10, #ff0f1a1d, #ff9db6ad, #ff080d10, #ff9db6ad, #ffb9828d, #ff0f1a1d, #ffd7dbd2, #ff0f1a1d, #ffd7dbd2, #808b9892

[Fonts]
fixed="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"
general="Cantarell,10,-1,5,50,0,0,0,0,0"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
menus_have_icons=true
show_shortcuts_in_context_menus=true
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3
